### ISSUE TITLE
Automatically add u-featured class to Post Thumbnail

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/bridgy-publish#30]
I'm not sure if this was discussed/considered previously outside of a few brief IRC conversations, but it could be useful for bridgy-publish to automatically add a `u-featured` class to the [Post Thumbnail/Featured Image](https://codex.wordpress.org/Post_Thumbnails) as most themes won't know about it and many users will appreciate having a photo in their tweets when cross posted via brid.gy.

@miklb described a custom function for doing this in https://miklb.com/microformats2-wordpress-and-featured-images-classes/ (and also made the suggestion for Bridgy Publish plugin to support it.)

Bridgy now supports `u-featured` natively as well: see https://github.com/snarfed/bridgy/issues/741

From a UI perspective, it would be nice to have an on/off toggle in settings for those who wouldn't want this, already support it, or who rely on OG metadata for twitter cards in conjunction with included links.

**Comment by miklb** [comment]
One thought I had was to look into whether there's a way to add a checkbox to the options screen before you insert the image as the featured image. If so, might be handy to add one to regular images to add the `u-photo` class for photo posts.

May be something for the IndieWeb plugin, since not everyone may use brid.gy but may want option to use the classes for other POSSE.

**Comment by dshanske** [comment]
Since I am planning on deprecating the plugin, marking these closed.
