### ISSUE TITLE
Syndication when publishing via Quill not working

### ISSUE THREAD

**Issue by ngm** [dshanske/bridgy-publish#40]
I have Micropub 1.2 and Bridgy 1.3.0 plugins installed.

When publishing via Quill, I can see and select the option for Twitter via Bridgy Publish.  However, it doesn't syndicate out to Twitter.

As far as I can tell it's because Quill sends `mp-syndicate-to`, which gets stored in wp_postmeta as `mf2_mp-syndicate-to`, whereas when the `services` method in `class-bridgy-postmeta.php` called by `wp_footer` is checking to see if a Twitter link should be added it is checking for `mf2_syndicate-to` (i.e. without the `mp`).

It's here:

https://github.com/dshanske/bridgy-publish/blob/19eee6a66ad9a75c477e83ea9ab816e2e3d9e72d/includes/class-bridgy-postmeta.php#L184

If I change that line to

    $metas = get_post_meta( $post_id, 'mf2_mp-syndicate-to', true );

then the syndication via a Quill publish works.

**Comment by Ruxton** [comment]
Similarly OwnYourGram (and anything else micropub) isn't syndicating.

It's because there is actually nothing that runs at micropub posting time, I've got a fix in the works to take care of this.  The only time bridgy-publish syndicates at present, is when you post from the WP admin ui and check the boxes.

This is what I'm working with at the moment, haven't had a chance to test it as OWG is down - https://github.com/Ruxton/bridgy-publish/tree/feature/micropub_bridgy

**Comment by dshanske** [comment]
Updated in latest dev version. It changed since the last time I added the feature.
